version: '3.8'

services:
  postgres:
    image: postgres:17.5
    container_name: rememberme-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rememberme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - rememberme-network

networks:
  rememberme-network:
    driver: bridge

volumes:
  postgres-data:
