version: '3.8'

services:
  backend:
    image: rememberme-backend:latest
    container_name: rememberme-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rememberme
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - rememberme-network

  postgres:
    image: postgres:17.5
    container_name: rememberme-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rememberme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - rememberme-network

networks:
  rememberme-network:
    driver: bridge

volumes:
  postgres-data:
