# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Spring configuration
spring:
  application:
    name: RememberMe
  ai:
    mcp:
      server:
        name: "remember-me-mcp-server"
        version: "1.0.0"
        type: SYNC
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
        base-url: /api


  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/rememberme
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Logging configuration
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Springdoc OpenAPI configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  packages-to-scan: com.example.rememberme
  paths-to-match: /**
