# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Spring configuration
spring:
  application:
    name: RememberMe
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/rememberme
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  
  # Jackson configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# Logging configuration
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE