# Development-specific configuration

# Server configuration
server:
  port: 8080

# Spring configuration
spring:
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/rememberme_dev
    username: postgres
    password: postgres
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  # Dev Tools
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE